error on empty inventory

diff --git a/.github/workflows/load_testing.yaml b/.github/workflows/load_testing.yaml
--- a/.github/workflows/load_testing.yaml
+++ b/.github/workflows/load_testing.yaml
@@ -85,11 +85,17 @@ jobs:
       - name: Generate list of host:port for config generator
         working-directory: node
         run: |
+          set -o pipefail
+
           sudo apt update && sudo apt install -y gettext-base
           tmp_inventory=$(cat ../infrastructure/loadtests/ansible/gcp.yml)
           echo "${tmp_inventory}" | envsubst > ../infrastructure/loadtests/ansible/gcp.yml
 
-          ansible-inventory -i ../infrastructure/loadtests/ansible/gcp.yml --list  | jq -r '.gcp_loadtest.hosts[]' | \
+          ansible-inventory -i ../infrastructure/loadtests/ansible/gcp.yml --list | \
+          tee /tmp/ansible_output.txt | \
+          grep -q "No inventory was parsed" && { echo "Error: No inventory was parsed."; exit 1; }
+
+          jq -r '.gcp_loadtest.hosts[]' < /tmp/ansible_output.txt | \
           awk -v port=${{ env.NODE_PORT }} -F\" '{print $1 ":" port}' > ips_prts.txt
 
       - name: Install node build dependencies
